---
- name: сreate directory
  hosts: server-one
  become: true
  tasks:
     - name: сreate directory
       file:
          path=/tmp/example_dir
          owner=root
          group=root        
          state=directory
     - name: Install htop 
       apt:
        name: htop
        state: present
     - name: Install tmux 
       apt:
        name: tmux
        state: present              